# rounded temperature sensors
- platform: template
  sensors:
    homelab_temperature_round:
      friendly_name: "Homelab Temperature"
      unit_of_measurement: '°C'
      value_template: "{{ (states('sensor.homelab_temperature') | float ) | round(1) }}"
      icon_template: mdi:thermometer

# rounded humidity sensors
- platform: template
  sensors:
    homelab_humidity_round:
      friendly_name: "Homelab Humidity"
      unit_of_measurement: '%'
      value_template: "{{ (states('sensor.homelab_humidity') | float ) | round(0) }}"
      icon_template: mdi:water-percent      
